# Programación para análisis de datos intro Numpy & Pandas

In [59]:
import numpy as np

In [60]:
A = [1, 2, 3, 4, 5]
type(A)

list

In [61]:
B = np.array([1, 2, 3, 4, 5])
type(B)

numpy.ndarray

In [62]:
import sys
# Size of array
size_array = sys.getsizeof(1) * len(A)
print(f"Size array A: {size_array}")
#Size of numpy array
size_numpy = B.itemsize * B.size
print(f"Size numpy: {size_numpy}")

Size array A: 140
Size numpy: 20


In [63]:
A = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [64]:
A.shape

(2, 5)

In [65]:
A.flatten().shape #Flatten junta todas las filas en una sola


(10,)

In [66]:
A.reshape(5, 2) 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [67]:
A.reshape(-1, 5) #-1 es el comodín, solo toma el otro valor como el número de columnas/filas a obtener

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [68]:
A.reshape(1, 1, -1)

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]])

In [69]:
B = np.arange(0, 100) #Con np.arange() creas datos dentro de un arreglo que siga ciertos parametros
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [70]:
zeros = np.zeros([10, 2])
print(zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [71]:
ones = np.ones([3, 9])
print(ones)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [72]:
A = [1, 2, 3]
A * 2

[1, 2, 3, 1, 2, 3]

In [73]:
A = np.array([1, 2, 3])
A * 2

array([2, 4, 6])

In [74]:
B = np.array([3, 4, 5])
A + B

array([4, 6, 8])

In [75]:
print(A, B)
A * B

[1 2 3] [3 4 5]


array([ 3,  8, 15])

In [76]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [77]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [78]:
print(A)

[1 2 3]


In [79]:
np.mean(A) #Media aritmetica

2.0

In [80]:
np.median(A) #Mediana

2.0

In [81]:
A = np.array([1, 2, 3, 0, 4, 5, 1, 3])
C = np.where(A > 2)
C

(array([2, 4, 5, 7], dtype=int64),)

# Dot product

In [82]:
def dot_product(a, b):
    result = 0
    for i in range(len(a)):
        result += a[i]*b[i]
    return result

In [83]:
a = np.random.randn(10000000)
b = np.random.randn(10000000)
print(dot_product(a, b))

12.059729665374794


In [84]:
import time
start = time.time()
dot_product(a,b)
total = time.time()- start
print(f"Total time: {total}")

Total time: 1.9582200050354004


In [85]:
np.dot(a, b)

12.059729665170607

In [86]:
start = time.time()
np.dot(a, b)
total = time.time()- start
print(f"Total time: {total}")

Total time: 0.012090444564819336
